// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package proto.xtdb.grpc.server;

public final class GrpcServerProto {
  private GrpcServerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_StatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_StatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_StatusReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_StatusReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014server.proto\022\006server\"\017\n\rStatusRequest\"" +
      "\036\n\013StatusReply\022\017\n\007message\030\001 \001(\t2@\n\006Serve" +
      "r\0226\n\006Status\022\025.server.StatusRequest\032\023.ser" +
      "ver.StatusReply\"\000B1\n\026proto.xtdb.grpc.ser" +
      "verB\017GrpcServerProtoP\001\242\002\003GRPb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_server_StatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_server_StatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_StatusRequest_descriptor,
        new java.lang.String[] { });
    internal_static_server_StatusReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_server_StatusReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_StatusReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
