// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package proto.xtdb.grpc.server;

public interface StatusReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.StatusReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
