// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package proto.xtdb.grpc.server;

public interface StatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.StatusRequest)
    com.google.protobuf.MessageOrBuilder {
}
